### ISSUE TITLE
Kód - A,B,C Algoritmusok átnézése és optimalizálása

### ISSUE THREAD

**Issue by O48WRX** [O48WRX/AFP_2022_2_K_10#7]
Az A,B,C algoritmusok teljes körű átnézése és esetleges optimalizálása, ha szükséges.

**Comment by RiczkoHenrik** [comment]
Átnéztem, minden rendben volt.

**Comment by BmihalyV** [comment]
Minden algoritmust átnéztem, minden rendben volt.

**Comment by HadobasDavid1** [comment]
Minden algoritmus rendben működik.
